name: Continuous Integration

on: pull_request

jobs: 
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Usung Nodejs
        uses: actions/setup-node@v2
        with: 
          node-version: 18.
      - name: run install, test and build
        run: |
          npm install
          npm run test
          npm run build     